# Generated by Django 3.0.5 on 2021-03-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=500)),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_Reason', models.CharField(max_length=800)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Approve'), (4, 'Rejected')], default=2, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
