# Generated by Django 3.0.5 on 2021-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.ManyToManyField(blank=True, to='employee.EmergencyContact'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.ManyToManyField(blank=True, to='employee.Experience'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='family_information',
            field=models.ManyToManyField(blank=True, to='employee.FamilyInformation'),
        ),
    ]
