# Generated by Django 3.0.5 on 2021-03-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('profile_picture', models.FileField(upload_to='')),
                ('designation', models.CharField(max_length=200)),
                ('clients_id', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('nid', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_deadline', models.DateField()),
                ('progress', models.IntegerField(default=0)),
                ('project_description', models.TextField()),
                ('project_files', models.FileField(upload_to='')),
                ('start_date', models.DateField()),
                ('is_delete', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients')),
            ],
        ),
    ]
