# Generated by Django 3.0.5 on 2021-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientsproject_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsproject',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
