# Generated by Django 3.1.6 on 2021-03-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_auto_20210322_1204'),
        ('clients', '0002_auto_20210322_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=256)),
                ('billing_address', models.CharField(max_length=256)),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('other_information', models.CharField(max_length=1000)),
                ('payment_type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Cheque')])),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Partially Paid')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='clients.clients')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='clients.clientsproject')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidentFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_share_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('employee_share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_share_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('company_share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provident_funds', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='accounts.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='accounts.tax'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('purchase_from', models.CharField(max_length=256)),
                ('purchase_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('payment_type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Cheque')])),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending')])),
                ('attached_slip', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses', to='employee.employee')),
            ],
        ),
    ]
