# Generated by Django 3.1.6 on 2021-03-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210323_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Cheque')], default=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending')], default=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Partially Paid')], default=1),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Cheque')], default=1),
        ),
    ]
