# Generated by Django 3.1.6 on 2021-03-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_subjects', models.CharField(max_length=200)),
                ('assign_staff', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Reopened'), (3, 'On Hold'), (4, 'Pending'), (5, 'InProgress'), (6, 'Canceled'), (7, 'Solved'), (8, 'New')], default=8)),
                ('description', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('is_delete', models.BooleanField(default=False)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clients')),
            ],
        ),
    ]
