# Generated by Django 3.1.6 on 2021-03-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('holiday_date', models.DateField()),
                ('day', models.CharField(max_length=200)),
            ],
        ),
    ]
